### ISSUE TITLE
script not running

### ISSUE THREAD

**Issue by sho-i98** [UBC-MDS/portugal_white_wine_quality_predictor_py#18]
Hello!
Unzipping script is not running on my end. Do you mind try running on your PC?

**Comment by jokittipong** [comment]
I found it!!!!
The error comes from the old url path is not working now (I don't know why too).
You need to change it to "https://archive.ics.uci.edu/static/public/186/wine+quality.zip"

**Comment by jokittipong** [comment]
FYI, I already changed the command in README.md!!
