### ISSUE TITLE
Announce some change on environment.yml

### ISSUE THREAD

**Issue by jokittipong** [UBC-MDS/portugal_white_wine_quality_predictor_py#8]
Hi Nicole and Sho,
I just added pytest=7.4.0 in environment.yml (already committed on github) as we need to do the test.
Also in our local machines don't have pytest so you may install it by using command
conda install -y pytest=7.4.0
If you two already installed it, please comment on this issue to confirm, then I'll close this issue.
Thanks!!

**Comment by sho-i98** [comment]
Great! Now my test files should run as well!

**Comment by Nicole-Tu97** [comment]
Thanks for the update!
